kumuluzee:
  env:
    name: production
  graphql:
    mapping: graphql
    federation:
      enabled: false
    ui:
      enabled: true
    defaults:
      offset: 0
      limit: 20
  datasources:
    - jndi-name: jdbc/Faculty
      connection-url: jdbc:postgresql://localhost:5432/faculty
      username: postgres
      password: postgres
      pool:
        max-size: 20
