kumuluzee:
  graphql:
    federation:
      enabled: false
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:postgresql://localhost:5432/customers
      username: postgres
      password: postgres
      pool:
        max-size: 20
 
  security:
    keycloak:
      json: '{
               "realm": "customers-realm",
               "bearer-only": true,
               "auth-server-url": "http://localhost:8082/auth",
               "ssl-required": "external",
               "resource": "customers-api",
               "confidential-port": 0
             }'
